#!/bin/bash

# Setup variables to quickly switch between various modes
# Whether to use Ignition or Gazebo
use_ign=true

# Both false = No beacons; beacons1 = B01 and B02; beacons2 = B03 - B08
enable_beacons1=false
enable_beacons2=false

if [ "$1" == "start" ]; then
  echo "Starting MARBLE services..."

  # Default to using the cave environment
  if [ "$2" == "" ]; then
    world="cave"
  else
    world=$2
  fi


  # Select the world file to run
  if $use_ign; then
    if [ "$world" == "cave" ]; then
      scenario="simple_cave_01"
      ignlaunch="cave_circuit.ign"
    elif [ "$world" == "urban" ]; then
      scenario="urban_circuit_practice_01"
      ignlaunch="urban_circuit.ign"
    elif [ "$world" == "tunnel" ]; then
      scenario="tunnel_circuit_practice_01"
      ignlaunch="tunnel_circuit_practice.ign"
    fi

    # Overwrite the world name if it was passed by command line
    if [ "$3" != "" ]; then
      scenario=$3
    fi

    beacons=""
    if $enable_beacons1; then
      beacons="robotName4:=B01 robotConfig4:=marble_beacon robotName5:=B02 robotConfig5:=marble_beacon"
    fi
    if $enable_beacons2; then
      beacons="robotName4:=B01 robotConfig4:=marble_beacon robotName5:=B02 robotConfig5:=marble_beacon robotName6:=B03 robotConfig6:=marble_beacon robotName7:=B04 robotConfig7:=marble_beacon robotName8:=B05 robotConfig8:=marble_beacon robotName9:=B06 robotConfig9:=marble_beacon robotName10:=B07 robotConfig10:=marble_beacon robotName11:=B08 robotConfig11:=marble_beacon"
    fi
    # Launch Ignition
    # ign launch $ignlaunch worldName:=$scenario robotName1:=X1 robotConfig1:=marble_husky_sensor_config_1 robotName2:=X2 robotConfig2:=marble_husky_sensor_config_1 robotName3:=Base robotConfig3:=X2_SENSOR_CONFIG_1 enableGroundTruth:=1 localModel:=true &
    ign launch $ignlaunch worldName:=$scenario robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_4 robotName2:=X2 robotConfig2:=X1_SENSOR_CONFIG_4 robotName3:=Base robotConfig3:=X2_SENSOR_CONFIG_1  enableGroundTruth:=1 $beacons localModel:=true &
    sleep 10
  else
    export X1_SENSOR_CONFIG_4=1

    if [ "$3" == "" ]; then
      if [ "$world" == "cave" ]; then
        scenario="tunnel_practice_2"
      elif [ "$world" == "urban" ]; then
        scenario="urban_underground"
      elif [ "$world" == "tunnel" ]; then
        scenario="tunnel_practice_2"
      fi
    else
      scenario=$3
    fi
  fi

  # Run our launch file
  roslaunch ~/marble/scripts/subt.launch use_ign:=$use_ign scenario:=$scenario beacons1:=$enable_beacons1 beacons2:=$enable_beacons2 &
  sleep 10

  # Run the python scripts
  # TF Transforms
  if ! $use_ign; then
    echo "Starting World to Bot TF..."
    python2 ~/marble/scripts/world_to_bot_tf.py &
  fi
  # Odometry correction
  python2 ~/marble/scripts/subt_true_odom.py X1 &
  python2 ~/marble/scripts/subt_true_odom.py X2 &

  # Start comms
  if $enable_beacons2; then
    python2 ~/catkin/src/marble_multi_agent/src/comms_sim_handler.py Base B01 B02 B03 B04 B05 B06 B07 B08 X1 X2 &
  elif $enable_beacons1; then
    python2 ~/catkin/src/marble_multi_agent/src/comms_sim_handler.py Base B01 B02 X1 X2 &
  else
    python2 ~/catkin/src/marble_multi_agent/src/comms_sim_handler.py Base X1 X2 &
  fi

  sleep 5

  # Turn on headlights.  See if we can move to launch file
  # ~/marble/scripts/marble lights

  # Start the comms checker
  ~/marble/scripts/marble commscheck

  # Start Multi-Agent nodes
  # ~/marble/scripts/marble map
  # ~/marble/scripts/marble multiagent

  # Run Frontier Exploration
  # ~/marble/scripts/marble explore_frontier

  sleep 10
  roslaunch ~/marble/scripts/rviz.launch &

elif [ "$1" == "stop" ]; then
  if [ "$2" == "explore_frontier" ]; then
    echo "Stopping MARBLE frontier exploration..."
    kill -9 $(pgrep -f 'python2.*subt_guidance_node.py')
    kill -9 $(pgrep -f 'python.*msfm3d')
    kill -9 $(pgrep -f 'msfm3d.*octomap')
    rosnode kill X1/global_planning
    rosnode kill X2/global_planning
  elif [ "$2" == "explore_graph" ]; then
    echo "Stopping MARBLE graph exploration..."
    rosnode kill X1/centering
    rosnode kill X1/cmd_vel_switch
    rosnode kill X1/gbm_node
    rosnode kill X1/graph2path
    rosnode kill X1/graphmsg2rviz
    rosnode kill X1/map2graph
    rosnode kill X2/centering
    rosnode kill X2/cmd_vel_switch
    rosnode kill X2/gbm_node
    rosnode kill X2/graph2path
    rosnode kill X2/graphmsg2rviz
    rosnode kill X2/map2graph
    kill -9 $(pgrep -f 'python.*graph.*.py')
    killall -HUP gbm_node
  elif [ "$2" == "map" ]; then
    echo "Stopping Map Merge nodes..."
    rosnode kill Base/octomap_merger
    rosnode kill X1/octomap_merger
    rosnode kill X2/octomap_merger
  elif [ "$2" == "multiagent" ]; then
    echo "Stopping MARBLE Multi-Agent nodes..."
    # kill -9 $(pgrep -f 'python2.*multi_agent.py')
    rosnode kill Base/multi_agent
    rosnode kill X1/multi_agent
    rosnode kill X2/multi_agent
    rosnode kill Base/get_map_diffs
    rosnode kill X1/get_map_diffs
    rosnode kill X2/get_map_diffs
    if $enable_beacons1; then
      rosnode kill B01/multi_agent
      rosnode kill B02/multi_agent
    fi
    if $enable_beacons2; then
      rosnode kill B03/multi_agent
      rosnode kill B04/multi_agent
      rosnode kill B05/multi_agent
      rosnode kill B06/multi_agent
      rosnode kill B07/multi_agent
      rosnode kill B08/multi_agent
    fi
  elif [ "$2" == "commscheck" ]; then
    echo "Stopping MARBLE Comms Check nodes..."
    kill -9 $(pgrep -f 'python2.*comms_sim_checker.py')

  else
    echo "Stopping MARBLE services..."
    rosnode kill -a
    killall -9 gzserver
    killall -9 rosmaster
    kill -9 $(pgrep -f 'ros_ign')
    kill -9 $(pgrep -f 'roslaunch')
    kill -9 $(pgrep -f 'ign launch')
    kill -9 $(pgrep -f 'python.*msfm3d')
    kill -9 $(pgrep -f 'msfm3d.*octomap')
    kill -9 $(pgrep -f 'python.*graph.*.py')
    # kill -9 $(pgrep -f 'python2.*multi_agent.py')
    kill -9 $(pgrep -f 'python2.*comms_sim_checker.py')
    kill -9 $(pgrep -f 'python2.*comms_sim_handler.py')
    kill -9 $(pgrep -f 'python2.*world_to_bot_tf.py')
    kill -9 $(pgrep -f 'python2.*subt_true_odom.py')
    kill -9 $(pgrep -f 'python2.*subt_guidance_node.py')
    kill -9 $(pgrep -f 'ros')
    killall -HUP gbm_node
  fi
elif [ "$1" == "explore_frontier" ]; then
  echo "Starting MARBLE Frontier exploration..."
  # rostopic pub /X1/cmd_vel geometry_msgs/Twist -1 -- '[1, 0, 0]' '[0, 0, 0]'
  # rostopic pub /X1/cmd_vel geometry_msgs/Twist -1 -- '[1, 0, 0]' '[0, 0, 0]'
  # rostopic pub /X1/cmd_vel geometry_msgs/Twist -1 -- '[1, 0, 0]' '[0, 0, 0]'
  roslaunch msfm3d msfm3d_ma.launch vehicle:=X1 &
  python2 ~/marble/scripts/subt_guidance_node.py "X1" "ground" "L2" 1.0 &

  # sleep 30
  # rostopic pub /X2/cmd_vel geometry_msgs/Twist -1 -- '[1, 0, 0]' '[0, 0, 0]'
  # rostopic pub /X2/cmd_vel geometry_msgs/Twist -1 -- '[1, 0, 0]' '[0, 0, 0]'
  # rostopic pub /X2/cmd_vel geometry_msgs/Twist -1 -- '[1, 0, 0]' '[0, 0, 0]'
  roslaunch msfm3d msfm3d_ma.launch vehicle:=X2 &
  python2 ~/marble/scripts/subt_guidance_node.py "X2" "ground" "L2" 1.0 &
elif [ "$1" == "explore_graph" ]; then
  echo "Starting MARBLE Graph exploration..."
  roslaunch graph-planner centering.launch vehicle:=X1 &
  roslaunch graph-planner junction_switch.launch vehicle:=X1 &
  roslaunch graph-planner junction_planner.launch vehicle:=X1 &
  roslaunch graph-planner graph.launch vehicle:=X1 &
  sleep 60
  roslaunch graph-planner centering.launch vehicle:=X2 &
  roslaunch graph-planner junction_switch.launch vehicle:=X2 &
  roslaunch graph-planner junction_planner.launch vehicle:=X2 &
  roslaunch graph-planner graph.launch vehicle:=X2 &

elif [ "$1" == "map" ]; then
  echo "Starting MARBLE Map Merge nodes..."
  roslaunch octomap_merger octomap_merger_sim.launch vehicle:=Base type:=base fullMerge:=true publishMergedPCL:=false publishDiffPCL:=true &
  roslaunch octomap_merger octomap_merger_sim.launch vehicle:=X1 &
  roslaunch octomap_merger octomap_merger_sim.launch vehicle:=X2 resolution:=0.2 &

elif [ "$1" == "multiagent" ]; then
  echo "Starting MARBLE Multi-Agent nodes..."
  roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=Base type:=base &
  roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=X1 myBeacons:="" delayDrop:=False &
  # roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=X1 myBeacons:="B01,B02,B03,B04" delayDrop:=False &
  roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=X2 myBeacons:="" &
  # roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=X2 myBeacons:="B05,B06,B07,B08" &
  if $enable_beacons1; then
    roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=B01 type:=beacon &
    roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=B02 type:=beacon &
  fi
  if $enable_beacons2; then
    roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=B03 type:=beacon &
    roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=B04 type:=beacon &
    roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=B05 type:=beacon &
    roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=B06 type:=beacon &
    roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=B07 type:=beacon &
    roslaunch marble_multi_agent multi_agent_sim.launch vehicle:=B08 type:=beacon &
  fi

elif [ "$1" == "commscheck" ]; then
  echo "Starting MARBLE Comms Check nodes..."
  python2 ~/catkin/src/marble_multi_agent/src/comms_sim_checker.py Base &
  python2 ~/catkin/src/marble_multi_agent/src/comms_sim_checker.py X1 &
  python2 ~/catkin/src/marble_multi_agent/src/comms_sim_checker.py X2 &
  if $enable_beacons1; then
    python2 ~/catkin/src/marble_multi_agent/src/comms_sim_checker.py B01 &
    python2 ~/catkin/src/marble_multi_agent/src/comms_sim_checker.py B02 &
  fi
  if $enable_beacons2; then
    python2 ~/catkin/src/marble_multi_agent/src/comms_sim_checker.py B03 &
    python2 ~/catkin/src/marble_multi_agent/src/comms_sim_checker.py B04 &
    python2 ~/catkin/src/marble_multi_agent/src/comms_sim_checker.py B05 &
    python2 ~/catkin/src/marble_multi_agent/src/comms_sim_checker.py B06 &
    python2 ~/catkin/src/marble_multi_agent/src/comms_sim_checker.py B07 &
    python2 ~/catkin/src/marble_multi_agent/src/comms_sim_checker.py B08 &
  fi

elif [ "$1" == "lights" ]; then
  echo "Turning on lights..."
  rosservice call /X1/left_headlight/enable "data: true"
  rosservice call /X1/right_headlight/enable "data: true"
  rosservice call /X2/left_headlight/enable "data: true"
  rosservice call /X2/right_headlight/enable "data: true"
else
  echo "Please tell me if you want to start, stop or explore!"
fi
