#!/bin/bash
source "$HOME/base_station/base_config"

if [ $MA_USEMESH == "true" ]; then
  echo "Launching UDP Mesh"
  roslaunch ~/base_station/udpmesh.launch mesh_interface:=$MA_INTERFACE
else
  echo "Launching multimaster"
  roslaunch ~/base_station/multimaster.launch
fi
